server:
  port: 30000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tECyTHFcgzs6MkyEEZB
      secret-key: MW6l2W64HedlZ0edAPnlYeWcUK5rzb
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: timechuchen-gulimall
  application:
    name: gulimall-third-party